[server]
maxMessageSize = 200
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#1E293B"
primaryColor = "#2563EB"
font = "sans serif"
